language: perl
perl:
  - "5.18-shrplib"
env: 
  - PERL_CPANM_OPT="--notest --force --skip-satisfied"
  - PATH=$PATH:./mash-Linux64-v1.1.1
before_install:
  - sudo apt-get update
  - sudo apt-get install sqlite3 libsqlite3-dev
  # bootstrap modules needed to manipulate dist
  - "yes no | cpanm --force --notest Bio::Perl"
  - cpanm -v -L . DBD::SQLite
  - wget https://github.com/marbl/Mash/releases/download/v1.1.1/mash-Linux64-v1.1.1.tar.gz
  - tar zxvf mash-Linux64-v1.1.1.tar.gz
#  - "cpanm Bio::Tree::DistanceFactory"
#  - "cpanm Bio::Matrix::IO"
#  - "cpanm Bio::Tree::Statistics"
#  - "cpanm DBD::SQLite"

