language: perl
perl:
  - "5.24-shrplib"
env: PERL_CPANM_OPT="--notest --force --skip-satisfied"
before_install:
  - sudo apt-get update
  - sudo apt-get install sqlite3 libsqlite3-dev
  # bootstrap modules needed to manipulate dist
  - "yes no | cpanm --force --notest Bio::Perl"
  - cpanm -v -L . DBD::SQLite
  #- "yes no | cpanm --force --notest DBI"
  - wget https://github.com/marbl/Mash/releases/download/v2.0/mash-Linux64-v2.0.tar.gz
  - tar zxvf mash-Linux64-v2.0.tar.gz
#  - "cpanm Bio::Tree::DistanceFactory"
#  - "cpanm Bio::Matrix::IO"
#  - "cpanm Bio::Tree::Statistics"
#  - "cpanm DBD::SQLite"
before_script:
  - PATH=$PATH:./mash-Linux64-v2.0
